server:
  port: 8080

spring:
  application:
    name: monitor-service

  datasource:
    url: jdbc:postgresql://localhost:5432/alertify_monitor
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: WARN